title: Knirpslarsi
description: Meine persönliche Website
url: "https://knirpslarsi.github.io"
baseurl: ""
theme: null

# Markdown processor
markdown: kramdown

# Build settings
exclude:
  - .gitignore
  - README.md

# Social Links (einfach URLs hier anpassen)
social:
  github: "https://github.com/Knirpslarsi"
  twitch: "https://twitch.tv/knirpslarsi_"
  discord: "https://discord.gg/jfwu8KjWqJ"

# Projects (einfach neue hinzufügen oder auskommentieren)
projects:
  - id: "larsium-v2"
    title: "Larsium V2"
    description: "A multifunctional Discord bot featuring moderation, utility commands, automation, and custom server management tools. Built to enhance community engagement and simplify server administration."
  - id: "karl-bot"
    title: "Karl"
    description: "Discord bot for TakeItIsy featuring a ticket system, counting game, and automated birthday notifications."
  - id: "larsiqr-studio"
    title: "LarsiQR Studio"
    description: "Simple Tool for creating QR Codes with a simple interface."
  #- id: "project-four"
  #  title: "Project Four"
  #  description: "A creative experiment blending design and functionality."
  #- id: "project-five"
  #  title: "Project Five"
  #  description: "Collaboration with talented designers and developers."
  #- id: "project-six"
  #  title: "Project Six"
  #  description: "Latest venture into emerging technologies."
